//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(IncidenceMetadata))]
    public partial class Incidence
    {
        public int IDIncidence { get; set; }
        public long IDUser { get; set; }
        public string Description { get; set; }
        public bool Finished { get; set; }
    
        public virtual User User { get; set; }
    }
}
