//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ReservationMetadata))]
    public partial class Reservation
    {
        public int IDReservation { get; set; }
        public long IDUser { get; set; }
        public int IDArea { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
    }
}
